/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Oscar R (https://sketchfab.com/braidoner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-low-poly-tatooine-skybox-4acf1cbebe674e128b4bf68e9897ae3e
Title: Star Wars - Low Poly Tatooine Skybox
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

import backgroundScene from '../assets/3d/star_wars_-_low_poly_tatooine_skybox.glb'

const Background = () => {
    const background = useGLTF(backgroundScene)

  return (
    <mesh>
        <primitive object={background.scene}/>
    </mesh>
  )
}

export default Background
