/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: drei.lu (https://sketchfab.com/drei.lu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-exploration-wlp-series-8-91964c1ce1a34c3985b6257441efa500
Title: Space exploration [WLP series #8]
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import exploreScene from '../assets/3d/space_exploration.glb'

const Explore = (props) => {
    const exploreRef = useRef();
  const { nodes, materials } = useGLTF(exploreScene)
  return (
    <a.group ref={exploreRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.003, 30.024, -2.331]} rotation={[0.238, -0.545, 0.562]} scale={7}>
          <mesh geometry={nodes.planet001_1.geometry} material={materials.scene} />
          <mesh geometry={nodes.planet001_2.geometry} material={materials.scene} />
        </group>
      </group>
    </a.group>
  )
}

export default Explore;
