/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Yo.Ri (https://sketchfab.com/grox777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/purple-planet-264eb22207184fc99a5e3b1279a763b8
Title: Purple Planet
*/

import { useRef, useEffect } from 'react'
import { useGLTF} from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import purplePlanetScene from '../assets/3d/purple_planet.glb';

const PurplePlanet = (props) => {
  const purplePlanetRef = useRef()
  const { nodes, materials} = useGLTF(purplePlanetScene)
  return (
    <a.group ref={purplePlanetRef} {...props}>
        <group name="Root">
            <group name="Planet" rotation={[0, 0, Math.PI / 2]}>
                <mesh
                    name="Planet_0"
                    geometry={nodes.Planet_0.geometry}
                    material={materials.PurplePlanet}
                />
                <group name="Clouds_0" rotation={[0, 0, -Math.PI / 2]} scale={1.013}>
                    <mesh
                    name="Clouds_0_0"
                    geometry={nodes.Clouds_0_0.geometry}
                    material={materials.Clouds_0}
                    />
                </group>
            </group>
            <group name="Clouds_1" scale={1.019}>
                <mesh
                    name="Clouds_1_0"
                    geometry={nodes.Clouds_1_0.geometry}
                    material={materials.Clouds_1}
                />
            </group>
        </group>
    </a.group>
  )
}

export default PurplePlanet;
